openapi: 3.0.3
info:
  title: Scripta API Documentation
  version: 1.0.0
  description: Endpoints for the Scripta application

servers:
  - url: http://localhost:4000
    description: Local development server

paths:
  /health:
    get:
      summary: Health check
      tags: [System]
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok

  /api/auth/register:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: babajide
                email:
                  type: string
                  example: babajide@example.com
                password:
                  type: string
                  format: password
                  example: strongpass123
                confirmPassword:
                  type: string
                  format: password
                  example: strongpass123
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Registration successful
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
                  token:
                    type: string
        '400':
          description: Validation or existing user error

  /api/auth/login:
    post:
      summary: Log in user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                identifier:
                  type: string
                  description: username or email
                  example: babajide
                password:
                  type: string
                  format: password
                  example: strongpass123
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successful
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
                  token:
                    type: string
        '400':
          description: Invalid credentials

  /api/me:
    get:
      summary: Get current user
      description: Returns the decoded JWT user info
      tags: [Auth]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User info retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id: { type: string }
                      username: { type: string }
                      email: { type: string }
        '401':
          description: Unauthorized — missing or invalid token

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
